name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests with Coverage
        run: pytest --cov=app --cov-report=term-missing -v

      - name: Generate coverage report
        run: pytest --cov=app --cov-report=xml --cov-report=html -v

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov

      - name: Notify Slack on Failure
        if: failure()
        run: |
          if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            curl -X POST "${{ secrets.SLACK_WEBHOOK_URL }}" \
              -H "Content-Type: application/json" \
              -d '{
                "text": "🚨 **CI/CD Pipeline Failed**\n• Repository: `${{ github.repository }}`\n• Workflow: `${{ github.workflow }}`\n• Branch: `${{ github.ref_name }}`\n• Triggered by: `${{ github.actor }}`\n• Commit: `${{ github.sha }}`\n• View Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "username": "GitHub Actions",
                "icon_emoji": ":warning:"
              }'
          else
            echo "SLACK_WEBHOOK_URL not configured, skipping Slack notification"
          fi

      - name: Notify Webhook Endpoint (Backup)
        if: failure()
        continue-on-error: true
        run: |
          if [ -n "${{ secrets.WEBHOOK_URL }}" ]; then
            curl -X POST "${{ secrets.WEBHOOK_URL }}/github-webhook" \
              -H "Content-Type: application/json" \
              -d '{
                "workflow_run": {
                  "conclusion": "failure",
                  "name": "${{ github.workflow }}",
                  "head_branch": "${{ github.ref_name }}"
                },
                "repository": {
                  "full_name": "${{ github.repository }}"
                },
                "sender": {
                  "login": "${{ github.actor }}"
                }
              }' || echo "Webhook notification failed"
          else
            echo "WEBHOOK_URL not configured, skipping webhook notification"
          fi
