name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests with Coverage
        run: pytest --cov=app --cov-report=term-missing -v

      - name: Generate coverage report
        run: pytest --cov=app --cov-report=xml --cov-report=html -v

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov

      - name: Notify on Build Failure
        if: failure()
        run: |
          curl -X POST "${{ secrets.WEBHOOK_URL }}/github-webhook" \
            -H "Content-Type: application/json" \
            -d '{
              "workflow_run": {
                "conclusion": "failure",
                "name": "${{ github.workflow }}",
                "head_branch": "${{ github.ref_name }}"
              },
              "repository": {
                "full_name": "${{ github.repository }}"
              },
              "sender": {
                "login": "${{ github.actor }}"
              }
            }'
